import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import Navbar from '@/components/Navigation/NavBar'
export const metadata: Metadata = {
  title: 'Kols Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className='px-8 min-h-screen flex justify-center items-center'>
            {children}
            {modal}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
